/* soapH.h
   Generated by gSOAP 2.8.11 from quote.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#ifndef soap_write_time
#define soap_write_time(soap, data) ( soap_begin_send(soap) || soap_put_time(soap, data, "dateTime", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);

#ifndef soap_read_time
#define soap_read_time(soap, data) ( soap_begin_recv(soap) || !soap_get_time(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef soap_write_bool
#define soap_write_bool(soap, data) ( soap_begin_send(soap) || soap_put_bool(soap, data, "boolean", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);

#ifndef soap_read_bool
#define soap_read_bool(soap, data) ( soap_begin_recv(soap) || !soap_get_bool(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);

#ifndef SOAP_TYPE__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult
#define SOAP_TYPE__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(struct soap*, const char*, int, const _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult *, const char*);
SOAP_FMAC3 _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult * SOAP_FMAC4 soap_in__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(struct soap*, const char*, _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult *, const char*);

#ifndef soap_write__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult
#define soap_write__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:GetQuoteDataSetResponse-GetQuoteDataSetResult", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult
#define soap_read__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult * SOAP_FMAC4 soap_get__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(struct soap*, _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult *, const char*, const char*);

#define soap_new__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(soap, n) soap_instantiate__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult * SOAP_FMAC2 soap_instantiate__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__DataSet
#define SOAP_TYPE__ns1__DataSet (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__DataSet(struct soap*, const char*, int, const _ns1__DataSet *, const char*);
SOAP_FMAC3 _ns1__DataSet * SOAP_FMAC4 soap_in__ns1__DataSet(struct soap*, const char*, _ns1__DataSet *, const char*);

#ifndef soap_write__ns1__DataSet
#define soap_write__ns1__DataSet(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:DataSet", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__DataSet
#define soap_read__ns1__DataSet(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__DataSet(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__DataSet * SOAP_FMAC4 soap_get__ns1__DataSet(struct soap*, _ns1__DataSet *, const char*, const char*);

#define soap_new__ns1__DataSet(soap, n) soap_instantiate__ns1__DataSet(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__DataSet(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__DataSet * SOAP_FMAC2 soap_instantiate__ns1__DataSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__DataSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetQuoteDataSetResponse
#define SOAP_TYPE__ns1__GetQuoteDataSetResponse (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetQuoteDataSetResponse(struct soap*, const char*, int, const _ns1__GetQuoteDataSetResponse *, const char*);
SOAP_FMAC3 _ns1__GetQuoteDataSetResponse * SOAP_FMAC4 soap_in__ns1__GetQuoteDataSetResponse(struct soap*, const char*, _ns1__GetQuoteDataSetResponse *, const char*);

#ifndef soap_write__ns1__GetQuoteDataSetResponse
#define soap_write__ns1__GetQuoteDataSetResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:GetQuoteDataSetResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__GetQuoteDataSetResponse
#define soap_read__ns1__GetQuoteDataSetResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetQuoteDataSetResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuoteDataSetResponse * SOAP_FMAC4 soap_get__ns1__GetQuoteDataSetResponse(struct soap*, _ns1__GetQuoteDataSetResponse *, const char*, const char*);

#define soap_new__ns1__GetQuoteDataSetResponse(soap, n) soap_instantiate__ns1__GetQuoteDataSetResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetQuoteDataSetResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetQuoteDataSetResponse * SOAP_FMAC2 soap_instantiate__ns1__GetQuoteDataSetResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetQuoteDataSetResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetQuoteDataSet
#define SOAP_TYPE__ns1__GetQuoteDataSet (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetQuoteDataSet(struct soap*, const char*, int, const _ns1__GetQuoteDataSet *, const char*);
SOAP_FMAC3 _ns1__GetQuoteDataSet * SOAP_FMAC4 soap_in__ns1__GetQuoteDataSet(struct soap*, const char*, _ns1__GetQuoteDataSet *, const char*);

#ifndef soap_write__ns1__GetQuoteDataSet
#define soap_write__ns1__GetQuoteDataSet(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:GetQuoteDataSet", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__GetQuoteDataSet
#define soap_read__ns1__GetQuoteDataSet(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetQuoteDataSet(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuoteDataSet * SOAP_FMAC4 soap_get__ns1__GetQuoteDataSet(struct soap*, _ns1__GetQuoteDataSet *, const char*, const char*);

#define soap_new__ns1__GetQuoteDataSet(soap, n) soap_instantiate__ns1__GetQuoteDataSet(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetQuoteDataSet(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetQuoteDataSet * SOAP_FMAC2 soap_instantiate__ns1__GetQuoteDataSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetQuoteDataSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetQuickQuoteResponse
#define SOAP_TYPE__ns1__GetQuickQuoteResponse (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetQuickQuoteResponse(struct soap*, const char*, int, const _ns1__GetQuickQuoteResponse *, const char*);
SOAP_FMAC3 _ns1__GetQuickQuoteResponse * SOAP_FMAC4 soap_in__ns1__GetQuickQuoteResponse(struct soap*, const char*, _ns1__GetQuickQuoteResponse *, const char*);

#ifndef soap_write__ns1__GetQuickQuoteResponse
#define soap_write__ns1__GetQuickQuoteResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:GetQuickQuoteResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__GetQuickQuoteResponse
#define soap_read__ns1__GetQuickQuoteResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetQuickQuoteResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuickQuoteResponse * SOAP_FMAC4 soap_get__ns1__GetQuickQuoteResponse(struct soap*, _ns1__GetQuickQuoteResponse *, const char*, const char*);

#define soap_new__ns1__GetQuickQuoteResponse(soap, n) soap_instantiate__ns1__GetQuickQuoteResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetQuickQuoteResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetQuickQuoteResponse * SOAP_FMAC2 soap_instantiate__ns1__GetQuickQuoteResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetQuickQuoteResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetQuickQuote
#define SOAP_TYPE__ns1__GetQuickQuote (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetQuickQuote(struct soap*, const char*, int, const _ns1__GetQuickQuote *, const char*);
SOAP_FMAC3 _ns1__GetQuickQuote * SOAP_FMAC4 soap_in__ns1__GetQuickQuote(struct soap*, const char*, _ns1__GetQuickQuote *, const char*);

#ifndef soap_write__ns1__GetQuickQuote
#define soap_write__ns1__GetQuickQuote(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:GetQuickQuote", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__GetQuickQuote
#define soap_read__ns1__GetQuickQuote(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetQuickQuote(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuickQuote * SOAP_FMAC4 soap_get__ns1__GetQuickQuote(struct soap*, _ns1__GetQuickQuote *, const char*, const char*);

#define soap_new__ns1__GetQuickQuote(soap, n) soap_instantiate__ns1__GetQuickQuote(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetQuickQuote(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetQuickQuote * SOAP_FMAC2 soap_instantiate__ns1__GetQuickQuote(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetQuickQuote(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetQuoteResponse
#define SOAP_TYPE__ns1__GetQuoteResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetQuoteResponse(struct soap*, const char*, int, const _ns1__GetQuoteResponse *, const char*);
SOAP_FMAC3 _ns1__GetQuoteResponse * SOAP_FMAC4 soap_in__ns1__GetQuoteResponse(struct soap*, const char*, _ns1__GetQuoteResponse *, const char*);

#ifndef soap_write__ns1__GetQuoteResponse
#define soap_write__ns1__GetQuoteResponse(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:GetQuoteResponse", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__GetQuoteResponse
#define soap_read__ns1__GetQuoteResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetQuoteResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuoteResponse * SOAP_FMAC4 soap_get__ns1__GetQuoteResponse(struct soap*, _ns1__GetQuoteResponse *, const char*, const char*);

#define soap_new__ns1__GetQuoteResponse(soap, n) soap_instantiate__ns1__GetQuoteResponse(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetQuoteResponse(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetQuoteResponse * SOAP_FMAC2 soap_instantiate__ns1__GetQuoteResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetQuoteResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetQuote
#define SOAP_TYPE__ns1__GetQuote (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetQuote(struct soap*, const char*, int, const _ns1__GetQuote *, const char*);
SOAP_FMAC3 _ns1__GetQuote * SOAP_FMAC4 soap_in__ns1__GetQuote(struct soap*, const char*, _ns1__GetQuote *, const char*);

#ifndef soap_write__ns1__GetQuote
#define soap_write__ns1__GetQuote(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:GetQuote", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read__ns1__GetQuote
#define soap_read__ns1__GetQuote(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetQuote(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuote * SOAP_FMAC4 soap_get__ns1__GetQuote(struct soap*, _ns1__GetQuote *, const char*, const char*);

#define soap_new__ns1__GetQuote(soap, n) soap_instantiate__ns1__GetQuote(soap, n, NULL, NULL, NULL)


#define soap_delete__ns1__GetQuote(soap, p) soap_delete(soap, p)

SOAP_FMAC1 _ns1__GetQuote * SOAP_FMAC2 soap_instantiate__ns1__GetQuote(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetQuote(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__QuoteData
#define SOAP_TYPE_ns1__QuoteData (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__QuoteData(struct soap*, const char*, int, const ns1__QuoteData *, const char*);
SOAP_FMAC3 ns1__QuoteData * SOAP_FMAC4 soap_in_ns1__QuoteData(struct soap*, const char*, ns1__QuoteData *, const char*);

#ifndef soap_write_ns1__QuoteData
#define soap_write_ns1__QuoteData(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "ns1:QuoteData", NULL) || soap_end_send(soap) )
#endif


#ifndef soap_read_ns1__QuoteData
#define soap_read_ns1__QuoteData(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__QuoteData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__QuoteData * SOAP_FMAC4 soap_get_ns1__QuoteData(struct soap*, ns1__QuoteData *, const char*, const char*);

#define soap_new_ns1__QuoteData(soap, n) soap_instantiate_ns1__QuoteData(soap, n, NULL, NULL, NULL)


#define soap_delete_ns1__QuoteData(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns1__QuoteData * SOAP_FMAC2 soap_instantiate_ns1__QuoteData(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__QuoteData(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (9)
#endif

#define soap_default_xsd__decimal(soap, a) soap_default_std__string(soap, a)


#define soap_serialize_xsd__decimal(soap, a) soap_serialize_std__string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__decimal(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__decimal(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_xsd__decimal
#define soap_write_xsd__decimal(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "xsd:decimal", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__decimal(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_xsd__decimal
#define soap_read_xsd__decimal(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__decimal(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__decimal(struct soap*, std::string *, const char*, const char*);

#define soap_new_xsd__decimal(soap, n) soap_instantiate_xsd__decimal(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__decimal(soap, p) soap_delete(soap, p)


#define soap_instantiate_xsd__decimal soap_instantiate_std__string


#define soap_copy_xsd__decimal soap_copy_std__string

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, "string", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__GetQuoteDataSet_
#define SOAP_TYPE___ns1__GetQuoteDataSet_ (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetQuoteDataSet_(struct soap*, struct __ns1__GetQuoteDataSet_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetQuoteDataSet_(struct soap*, const struct __ns1__GetQuoteDataSet_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetQuoteDataSet_(struct soap*, const char*, int, const struct __ns1__GetQuoteDataSet_ *, const char*);
SOAP_FMAC3 struct __ns1__GetQuoteDataSet_ * SOAP_FMAC4 soap_in___ns1__GetQuoteDataSet_(struct soap*, const char*, struct __ns1__GetQuoteDataSet_ *, const char*);

#ifndef soap_write___ns1__GetQuoteDataSet_
#define soap_write___ns1__GetQuoteDataSet_(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__GetQuoteDataSet_(soap, data), 0) || soap_put___ns1__GetQuoteDataSet_(soap, data, "-ns1:GetQuoteDataSet", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetQuoteDataSet_(struct soap*, const struct __ns1__GetQuoteDataSet_ *, const char*, const char*);

#ifndef soap_read___ns1__GetQuoteDataSet_
#define soap_read___ns1__GetQuoteDataSet_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetQuoteDataSet_(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__GetQuoteDataSet_ * SOAP_FMAC4 soap_get___ns1__GetQuoteDataSet_(struct soap*, struct __ns1__GetQuoteDataSet_ *, const char*, const char*);

#define soap_new___ns1__GetQuoteDataSet_(soap, n) soap_instantiate___ns1__GetQuoteDataSet_(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__GetQuoteDataSet_(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__GetQuoteDataSet_ * SOAP_FMAC2 soap_instantiate___ns1__GetQuoteDataSet_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetQuoteDataSet_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GetQuickQuote_
#define SOAP_TYPE___ns1__GetQuickQuote_ (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetQuickQuote_(struct soap*, struct __ns1__GetQuickQuote_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetQuickQuote_(struct soap*, const struct __ns1__GetQuickQuote_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetQuickQuote_(struct soap*, const char*, int, const struct __ns1__GetQuickQuote_ *, const char*);
SOAP_FMAC3 struct __ns1__GetQuickQuote_ * SOAP_FMAC4 soap_in___ns1__GetQuickQuote_(struct soap*, const char*, struct __ns1__GetQuickQuote_ *, const char*);

#ifndef soap_write___ns1__GetQuickQuote_
#define soap_write___ns1__GetQuickQuote_(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__GetQuickQuote_(soap, data), 0) || soap_put___ns1__GetQuickQuote_(soap, data, "-ns1:GetQuickQuote", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetQuickQuote_(struct soap*, const struct __ns1__GetQuickQuote_ *, const char*, const char*);

#ifndef soap_read___ns1__GetQuickQuote_
#define soap_read___ns1__GetQuickQuote_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetQuickQuote_(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__GetQuickQuote_ * SOAP_FMAC4 soap_get___ns1__GetQuickQuote_(struct soap*, struct __ns1__GetQuickQuote_ *, const char*, const char*);

#define soap_new___ns1__GetQuickQuote_(soap, n) soap_instantiate___ns1__GetQuickQuote_(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__GetQuickQuote_(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__GetQuickQuote_ * SOAP_FMAC2 soap_instantiate___ns1__GetQuickQuote_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetQuickQuote_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GetQuote_
#define SOAP_TYPE___ns1__GetQuote_ (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetQuote_(struct soap*, struct __ns1__GetQuote_ *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetQuote_(struct soap*, const struct __ns1__GetQuote_ *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetQuote_(struct soap*, const char*, int, const struct __ns1__GetQuote_ *, const char*);
SOAP_FMAC3 struct __ns1__GetQuote_ * SOAP_FMAC4 soap_in___ns1__GetQuote_(struct soap*, const char*, struct __ns1__GetQuote_ *, const char*);

#ifndef soap_write___ns1__GetQuote_
#define soap_write___ns1__GetQuote_(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__GetQuote_(soap, data), 0) || soap_put___ns1__GetQuote_(soap, data, "-ns1:GetQuote", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetQuote_(struct soap*, const struct __ns1__GetQuote_ *, const char*, const char*);

#ifndef soap_read___ns1__GetQuote_
#define soap_read___ns1__GetQuote_(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetQuote_(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__GetQuote_ * SOAP_FMAC4 soap_get___ns1__GetQuote_(struct soap*, struct __ns1__GetQuote_ *, const char*, const char*);

#define soap_new___ns1__GetQuote_(soap, n) soap_instantiate___ns1__GetQuote_(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__GetQuote_(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__GetQuote_ * SOAP_FMAC2 soap_instantiate___ns1__GetQuote_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetQuote_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GetQuoteDataSet
#define SOAP_TYPE___ns1__GetQuoteDataSet (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetQuoteDataSet(struct soap*, struct __ns1__GetQuoteDataSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetQuoteDataSet(struct soap*, const struct __ns1__GetQuoteDataSet *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetQuoteDataSet(struct soap*, const char*, int, const struct __ns1__GetQuoteDataSet *, const char*);
SOAP_FMAC3 struct __ns1__GetQuoteDataSet * SOAP_FMAC4 soap_in___ns1__GetQuoteDataSet(struct soap*, const char*, struct __ns1__GetQuoteDataSet *, const char*);

#ifndef soap_write___ns1__GetQuoteDataSet
#define soap_write___ns1__GetQuoteDataSet(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__GetQuoteDataSet(soap, data), 0) || soap_put___ns1__GetQuoteDataSet(soap, data, "-ns1:GetQuoteDataSet", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetQuoteDataSet(struct soap*, const struct __ns1__GetQuoteDataSet *, const char*, const char*);

#ifndef soap_read___ns1__GetQuoteDataSet
#define soap_read___ns1__GetQuoteDataSet(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetQuoteDataSet(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__GetQuoteDataSet * SOAP_FMAC4 soap_get___ns1__GetQuoteDataSet(struct soap*, struct __ns1__GetQuoteDataSet *, const char*, const char*);

#define soap_new___ns1__GetQuoteDataSet(soap, n) soap_instantiate___ns1__GetQuoteDataSet(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__GetQuoteDataSet(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__GetQuoteDataSet * SOAP_FMAC2 soap_instantiate___ns1__GetQuoteDataSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetQuoteDataSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GetQuickQuote
#define SOAP_TYPE___ns1__GetQuickQuote (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetQuickQuote(struct soap*, struct __ns1__GetQuickQuote *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetQuickQuote(struct soap*, const struct __ns1__GetQuickQuote *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetQuickQuote(struct soap*, const char*, int, const struct __ns1__GetQuickQuote *, const char*);
SOAP_FMAC3 struct __ns1__GetQuickQuote * SOAP_FMAC4 soap_in___ns1__GetQuickQuote(struct soap*, const char*, struct __ns1__GetQuickQuote *, const char*);

#ifndef soap_write___ns1__GetQuickQuote
#define soap_write___ns1__GetQuickQuote(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__GetQuickQuote(soap, data), 0) || soap_put___ns1__GetQuickQuote(soap, data, "-ns1:GetQuickQuote", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetQuickQuote(struct soap*, const struct __ns1__GetQuickQuote *, const char*, const char*);

#ifndef soap_read___ns1__GetQuickQuote
#define soap_read___ns1__GetQuickQuote(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetQuickQuote(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__GetQuickQuote * SOAP_FMAC4 soap_get___ns1__GetQuickQuote(struct soap*, struct __ns1__GetQuickQuote *, const char*, const char*);

#define soap_new___ns1__GetQuickQuote(soap, n) soap_instantiate___ns1__GetQuickQuote(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__GetQuickQuote(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__GetQuickQuote * SOAP_FMAC2 soap_instantiate___ns1__GetQuickQuote(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetQuickQuote(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GetQuote
#define SOAP_TYPE___ns1__GetQuote (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetQuote(struct soap*, struct __ns1__GetQuote *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetQuote(struct soap*, const struct __ns1__GetQuote *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetQuote(struct soap*, const char*, int, const struct __ns1__GetQuote *, const char*);
SOAP_FMAC3 struct __ns1__GetQuote * SOAP_FMAC4 soap_in___ns1__GetQuote(struct soap*, const char*, struct __ns1__GetQuote *, const char*);

#ifndef soap_write___ns1__GetQuote
#define soap_write___ns1__GetQuote(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns1__GetQuote(soap, data), 0) || soap_put___ns1__GetQuote(soap, data, "-ns1:GetQuote", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetQuote(struct soap*, const struct __ns1__GetQuote *, const char*, const char*);

#ifndef soap_read___ns1__GetQuote
#define soap_read___ns1__GetQuote(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetQuote(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct __ns1__GetQuote * SOAP_FMAC4 soap_get___ns1__GetQuote(struct soap*, struct __ns1__GetQuote *, const char*, const char*);

#define soap_new___ns1__GetQuote(soap, n) soap_instantiate___ns1__GetQuote(soap, n, NULL, NULL, NULL)


#define soap_delete___ns1__GetQuote(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns1__GetQuote * SOAP_FMAC2 soap_instantiate___ns1__GetQuote(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetQuote(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_ns1__GetQuoteDataSetResponse
#define SOAP_TYPE_PointerTo_ns1__GetQuoteDataSetResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetQuoteDataSetResponse(struct soap*, _ns1__GetQuoteDataSetResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetQuoteDataSetResponse(struct soap*, const char *, int, _ns1__GetQuoteDataSetResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetQuoteDataSetResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetQuoteDataSetResponse(struct soap*, const char*, _ns1__GetQuoteDataSetResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__GetQuoteDataSetResponse
#define soap_write_PointerTo_ns1__GetQuoteDataSetResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetQuoteDataSetResponse(soap, data), 0) || soap_put_PointerTo_ns1__GetQuoteDataSetResponse(soap, data, "ns1:GetQuoteDataSetResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetQuoteDataSetResponse(struct soap*, _ns1__GetQuoteDataSetResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetQuoteDataSetResponse
#define soap_read_PointerTo_ns1__GetQuoteDataSetResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetQuoteDataSetResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuoteDataSetResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetQuoteDataSetResponse(struct soap*, _ns1__GetQuoteDataSetResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetQuoteDataSet
#define SOAP_TYPE_PointerTo_ns1__GetQuoteDataSet (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetQuoteDataSet(struct soap*, _ns1__GetQuoteDataSet *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetQuoteDataSet(struct soap*, const char *, int, _ns1__GetQuoteDataSet *const*, const char *);
SOAP_FMAC3 _ns1__GetQuoteDataSet ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetQuoteDataSet(struct soap*, const char*, _ns1__GetQuoteDataSet **, const char*);

#ifndef soap_write_PointerTo_ns1__GetQuoteDataSet
#define soap_write_PointerTo_ns1__GetQuoteDataSet(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetQuoteDataSet(soap, data), 0) || soap_put_PointerTo_ns1__GetQuoteDataSet(soap, data, "ns1:GetQuoteDataSet", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetQuoteDataSet(struct soap*, _ns1__GetQuoteDataSet *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetQuoteDataSet
#define soap_read_PointerTo_ns1__GetQuoteDataSet(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetQuoteDataSet(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuoteDataSet ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetQuoteDataSet(struct soap*, _ns1__GetQuoteDataSet **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetQuickQuoteResponse
#define SOAP_TYPE_PointerTo_ns1__GetQuickQuoteResponse (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetQuickQuoteResponse(struct soap*, _ns1__GetQuickQuoteResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetQuickQuoteResponse(struct soap*, const char *, int, _ns1__GetQuickQuoteResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetQuickQuoteResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetQuickQuoteResponse(struct soap*, const char*, _ns1__GetQuickQuoteResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__GetQuickQuoteResponse
#define soap_write_PointerTo_ns1__GetQuickQuoteResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetQuickQuoteResponse(soap, data), 0) || soap_put_PointerTo_ns1__GetQuickQuoteResponse(soap, data, "ns1:GetQuickQuoteResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetQuickQuoteResponse(struct soap*, _ns1__GetQuickQuoteResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetQuickQuoteResponse
#define soap_read_PointerTo_ns1__GetQuickQuoteResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetQuickQuoteResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuickQuoteResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetQuickQuoteResponse(struct soap*, _ns1__GetQuickQuoteResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetQuickQuote
#define SOAP_TYPE_PointerTo_ns1__GetQuickQuote (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetQuickQuote(struct soap*, _ns1__GetQuickQuote *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetQuickQuote(struct soap*, const char *, int, _ns1__GetQuickQuote *const*, const char *);
SOAP_FMAC3 _ns1__GetQuickQuote ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetQuickQuote(struct soap*, const char*, _ns1__GetQuickQuote **, const char*);

#ifndef soap_write_PointerTo_ns1__GetQuickQuote
#define soap_write_PointerTo_ns1__GetQuickQuote(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetQuickQuote(soap, data), 0) || soap_put_PointerTo_ns1__GetQuickQuote(soap, data, "ns1:GetQuickQuote", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetQuickQuote(struct soap*, _ns1__GetQuickQuote *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetQuickQuote
#define soap_read_PointerTo_ns1__GetQuickQuote(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetQuickQuote(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuickQuote ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetQuickQuote(struct soap*, _ns1__GetQuickQuote **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetQuoteResponse
#define SOAP_TYPE_PointerTo_ns1__GetQuoteResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetQuoteResponse(struct soap*, _ns1__GetQuoteResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetQuoteResponse(struct soap*, const char *, int, _ns1__GetQuoteResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetQuoteResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetQuoteResponse(struct soap*, const char*, _ns1__GetQuoteResponse **, const char*);

#ifndef soap_write_PointerTo_ns1__GetQuoteResponse
#define soap_write_PointerTo_ns1__GetQuoteResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetQuoteResponse(soap, data), 0) || soap_put_PointerTo_ns1__GetQuoteResponse(soap, data, "ns1:GetQuoteResponse", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetQuoteResponse(struct soap*, _ns1__GetQuoteResponse *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetQuoteResponse
#define soap_read_PointerTo_ns1__GetQuoteResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetQuoteResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuoteResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetQuoteResponse(struct soap*, _ns1__GetQuoteResponse **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetQuote
#define SOAP_TYPE_PointerTo_ns1__GetQuote (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetQuote(struct soap*, _ns1__GetQuote *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetQuote(struct soap*, const char *, int, _ns1__GetQuote *const*, const char *);
SOAP_FMAC3 _ns1__GetQuote ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetQuote(struct soap*, const char*, _ns1__GetQuote **, const char*);

#ifndef soap_write_PointerTo_ns1__GetQuote
#define soap_write_PointerTo_ns1__GetQuote(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetQuote(soap, data), 0) || soap_put_PointerTo_ns1__GetQuote(soap, data, "ns1:GetQuote", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetQuote(struct soap*, _ns1__GetQuote *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetQuote
#define soap_read_PointerTo_ns1__GetQuote(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetQuote(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuote ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetQuote(struct soap*, _ns1__GetQuote **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult
#define SOAP_TYPE_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(struct soap*, _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(struct soap*, const char *, int, _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult *const*, const char *);
SOAP_FMAC3 _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(struct soap*, const char*, _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult **, const char*);

#ifndef soap_write_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult
#define soap_write_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(soap, data), 0) || soap_put_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(soap, data, "ns1:GetQuoteDataSetResponse-GetQuoteDataSetResult", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(struct soap*, _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult *const*, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult
#define soap_read_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult(struct soap*, _ns1__GetQuoteDataSetResponse_GetQuoteDataSetResult **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons1__QuoteData
#define SOAP_TYPE_PointerTons1__QuoteData (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__QuoteData(struct soap*, ns1__QuoteData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__QuoteData(struct soap*, const char *, int, ns1__QuoteData *const*, const char *);
SOAP_FMAC3 ns1__QuoteData ** SOAP_FMAC4 soap_in_PointerTons1__QuoteData(struct soap*, const char*, ns1__QuoteData **, const char*);

#ifndef soap_write_PointerTons1__QuoteData
#define soap_write_PointerTons1__QuoteData(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons1__QuoteData(soap, data), 0) || soap_put_PointerTons1__QuoteData(soap, data, "ns1:QuoteData", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__QuoteData(struct soap*, ns1__QuoteData *const*, const char*, const char*);

#ifndef soap_read_PointerTons1__QuoteData
#define soap_read_PointerTons1__QuoteData(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons1__QuoteData(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 ns1__QuoteData ** SOAP_FMAC4 soap_get_PointerTons1__QuoteData(struct soap*, ns1__QuoteData **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);

#ifndef soap_write_PointerTostd__string
#define soap_write_PointerTostd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTostd__string(soap, data), 0) || soap_put_PointerTostd__string(soap, data, "string", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_read_PointerTostd__string
#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

/* _xsd__schema is a typedef element/attribute synonym for string */

#ifndef SOAP_TYPE__xsd__schema
#define SOAP_TYPE__xsd__schema (10)
#endif

#define soap_default__xsd__schema(soap, a) soap_default_string(soap, a)


#define soap_serialize__xsd__schema(soap, a) soap_serialize_string(soap, a)


#define soap_out__xsd__schema soap_out_string


#define soap_in__xsd__schema soap_in_string


#ifndef soap_write__xsd__schema
#define soap_write__xsd__schema(soap, data) ( soap_begin_send(soap) || (soap_serialize__xsd__schema(soap, data), 0) || soap_put__xsd__schema(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


#define soap_put__xsd__schema soap_put_string


#ifndef soap_read__xsd__schema
#define soap_read__xsd__schema(soap, data) ( soap_begin_recv(soap) || !soap_get__xsd__schema(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif


#define soap_get__xsd__schema soap_get_string


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#endif

/* End of soapH.h */
